# Name of website
title                  : JUST FENCING

# remote_theme: "mmistakes/so-simple-theme@3.2.0" 
# remote_theme: "mmistakes/so-simple-theme" 

# remote_theme: "mmistakes/minimal-mistakes" 
remote_theme: "mmistakes/jekyll-theme-basically-basic" 

# remote_theme: "pmarsceill/just-the-docs"
# Color scheme currently only supports "dark" or nil (default)
# color_scheme: "dark"
# search_enabled: false

# remote_theme: "mattgraham/midnight" # scheinbar nix 
# remote_theme: "mattvh/jekyllthemes" 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  
layout: page
