theme: jekyll-theme-minimal

minimal_mistakes_skin: "dark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  
# Name of website
title: Wiki Test 10

# Short description of your site
description: Wiki Test a virtual proof that I'm awesome

sidebar:
  nav: "docs"
  
docs:
  - title: Getting Started
    children:
      - title: "Quick-Start Guide"
        url: /fechter
      - title: "Structure"
        url: /trainer
      
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "docs" 
