plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  
# Name of website
title: Wiki Test 1

# Short description of your site
description: Wiki Test a virtual proof that I'm awesome
