plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  
relative_links:
  enabled: true
  collections: true

# Name of website
title: Wiki Test

# Short description of your site
description: Wiki Test a virtual proof that I'm awesome

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"
  
include:
  - fechter.md
  - trainer.md
  
  defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
      footer: footer
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
      footer: footer
  -
    scope:
      path: ""
      type: search
    values:
      layout: default
      topnav: topnav
      footer: footer
      type: search
      sidebar: jekyllhowto

  -
    scope:
      path: "images"
    values:
      image: true

