plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  
# Name of website
title: Wiki Test 3

# Short description of your site
description: Wiki Test a virtual proof that I'm awesome

defaults:
  - scope:
      path: _pages/intro
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "intro" 
  - scope:
      path: _pages/core
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "core"
