# Name of website
# title                  : Wiki Test 21

#remote_theme: "mmistakes/so-simple-theme@3.2.0" 
remote_theme: "mmistakes/so-simple-theme" 
# remote_theme: "pmarsceill/just-the-docs"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  
layout: page
