plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  
# Name of website
title: Wiki Test 2

# Short description of your site
description: Wiki Test a virtual proof that I'm awesome

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
